### ISSUE TITLE
Logo and navigation menu bar overlap

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar-site#13]
See the screenshot:
<img width="1257" alt="Screen Shot 2022-03-06 at 9 40 44 AM" src="https://user-images.githubusercontent.com/29803617/156935251-71402bd0-b3b0-4e7e-81d1-6d64e63c1082.png">

**Comment by dave2wave** [comment]
I'm not sure that this is setup correctly. as at one width it's ok but then a slightly wider window it's not. Can it always take the narrower approach
<img width="1171" alt="Screen Shot 2022-03-06 at 8 24 36 PM" src="https://user-images.githubusercontent.com/29803617/156968065-82b8b845-cc6c-43b5-9f5b-1e5d5ed82b2b.png">
<img width="1237" alt="Screen Shot 2022-03-06 at 8 24 51 PM" src="https://user-images.githubusercontent.com/29803617/156968082-23dda266-7a19-487d-a15e-52177fe6357c.png">
?

**Comment by urfreespace** [comment]
@dave2wave I think it had been fixed, PTAL again.
