### ISSUE TITLE
Provide structural client overview page

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-site#146]
Currently, Pulsar provides a [Client Libraries](https://pulsar.apache.org/docs/next/client-libraries) page to show official and third party client libraries.

While it's a good entry point for related resources, the structure of that page can be improved to deliver information more structural and impressive.

Here are three points I can see so far:

1. First of all, we should inline the feature matrix in the page, at least it should not be a dangling Google Doc sheet.
2. We can merge the feature matrix into the client table, and reduce redundant infos. For example, we don't have to show release notes but if it's valuable, add a link in the dedicate doc page.
3. We can display third party client libraries in a more heuristics way. Perhaps learn from [how Redis shows it client libraries](https://redis.io/docs/clients/).

Looking forward to your thoughts - whether these points are valid and if you have additional ideas in mind.

I'll prepare a draft to apply suggestions above in this month if there's no objection.

**Comment by tisonkun** [comment]
It seems that the source of related contents go into [apache/pulsar](http://github.com/apache/pulsar) repo. I'm going to create a patch for preview there.

**Comment by tisonkun** [comment]
* Beam shows their matrix as: https://beam.apache.org/documentation/runners/capability-matrix/
* Elastic shows their matrix as: https://www.elastic.co/support/matrix

**Comment by tisonkun** [comment]
After a closer look, I see that the feature matrix is too detailed to be inlined. I'd like to improve the display only.

For the feature matrix, it's mainly tracking feature points and whether it has a document entry. Once we add document to all those features, we may simply remove that matrix.

Closed and won't do. I'll send a patch on the display issues directly to apache/pulsar.

**Comment by momo-jun** [comment]
> For the feature matrix, it's mainly tracking feature points and whether it has a document entry. Once we add document to all those features, we may simply remove that matrix.

It would be helpful to both maintainers and users by showing the feature supportability of all clients on a doc page. When the docs are added, we can add doc links instead.
