### ISSUE TITLE
Improve color shades for dark mode

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-site#173]
Currently, in dark mode, the contents on several pages are hard to read.

For example, https://pulsar.apache.org/docs/next/tiered-storage-filesystem#configure-filesystem-offloader-driver.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/186356215-8b6e3d0f-0ded-4db4-9be7-d63c518f54bc.png">

cc @Anonymitaet @urfreespace

**Comment by Anonymitaet** [comment]
@tisonkun thanks for raising this up!

Even though the Pulsar website is built in the `pulsar-site` repo and many website-related data are hosted here, I still suggest reporting website-related issues in the `pulsar` repo. 

Reasons:

- High visibility, which means the issue can get more attention since the majority of ppl go to `pulsar`. Only a few ppl know `pulsar-site`.

- From past to now, we nearly track all website-related issues in `pulsar`, it's convenient for us to triage and check them all in one place.

Thoughts?

**Comment by tisonkun** [comment]
@Anonymitaet for this specific issue, I think we need UI experts to help with selecting colors series.

The related code is https://github.com/apache/pulsar-site/blob/e1785ad30a9bd02047ccd31e85e9c89fa1c37c6a/site2/website-next/src/css/custom.css while is hosted primary in this repo instead of synced from `pulsar`.

@urfreespace suggests I report site-related topics here and content-related topics in the main repo. Although, I agree on the "High visibility". I'm OK to just disable the issue tab in this repo and report all issues in `pulsar` - [SkyWalking](https://github.com/apache/skywalking) follows this pattern.

**Comment by Anonymitaet** [comment]
Hi designers, @gancunjie @DaveDuggins, is it a good practice to set all the texts in the dark color background to `white`?

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/50226895/186384398-a6b3c13f-b49b-457a-9895-64740cfe3c48.png">

**Comment by urfreespace** [comment]
fixed with this PR https://github.com/apache/pulsar-site/pull/180

**Comment by tisonkun** [comment]
Thanks! Although the color series seems can be continuously improved, now the content can be read clearly.

**Comment by tisonkun** [comment]
@urfreespace found one case inconsistent: https://pulsar.apache.org/versions/

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/186653261-503b381d-e7d4-4d62-9965-f15c7aa83ac3.png">

Could you reopen this issue or shall I open a new one?

**Comment by urfreespace** [comment]
> @urfreespace found one case inconsistent: https://pulsar.apache.org/versions/
> 
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/18818196/186653261-503b381d-e7d4-4d62-9965-f15c7aa83ac3.png">
> 
> Could you reopen this issue or shall I open a new one?

thanks for the report, reopened; I will take look

**Comment by urfreespace** [comment]
fixed https://github.com/apache/pulsar-site/pull/181, @tisonkun PTAL after some time, if it works well, pls help close this issue, thanks

**Comment by tisonkun** [comment]
Looks good now. And verify no regression on the original reported page.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/186662554-afa1b3ad-599b-449f-8ce7-4d8b9ff60e16.png">

Closing...

**Comment by labuladong** [comment]
Maybe this light-style table can be improved:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/37220920/187413231-71732844-72f6-4149-91a4-b6a0a4736cb9.png">

This dark-style table is better:

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/37220920/187413331-63ecbd09-ad5f-48ef-8f40-b239007cbdca.png">

@tisonkun @urfreespace @Anonymitaet What do you think?

**Comment by tisonkun** [comment]
@labuladong this change looks good :)

**Comment by Anonymitaet** [comment]
@labuladong +1
