### ISSUE TITLE
Migrate all docs from `/tools` to `/reference`

### ISSUE THREAD

**Issue by SignorMercurio** [apache/pulsar-site#177]
According to https://apache-pulsar.slack.com/archives/C03MG1H2B3N/p1661220553497289, we can start working on migrate all docs from `/tools` to `/reference`. For instance, https://pulsar.apache.org/tools/pulsar-admin/2.11.0-SNAPSHOT/ will be moved to https://pulsar.apache.org/reference/ and can be viewed in the `Pulsar Admin` section of the side navbar, just like `Pulsar Configuration` right now.

I'm currently working on this.

**Comment by tisonkun** [comment]
@SignorMercurio the link is broken for me. I don't find the referred discussion.

**Comment by SignorMercurio** [comment]
@tisonkun Sorry, perhaps due to it's a private discussion. I believe @Anonymitaet has sent an email asking for thoughts on this issue?

**Comment by Anonymitaet** [comment]
ML: 
https://lists.apache.org/thread/1g8nxqg4gdw3obq4wfgv442hvspk7ovy
