### ISSUE TITLE
Unable navigate to edit page due to dead link

### ISSUE THREAD

**Issue by maxsxu** [apache/pulsar-site#78]
### Description
The link of **Edit this page** is not found, which is `https://github.com/apache/pulsar/edit/master/site2/docs/about.md`.

### Reproduction
1. Open page https://pulsar.apache.org/docs/next/
2. Click [Edit this page](https://github.com/apache/pulsar/edit/master/site2/docs/about.md) at the bottom of this page

### Screenshots

<img width="433" alt="image" src="https://user-images.githubusercontent.com/15963141/168599215-4e560971-8890-458e-b18b-174b047adfa1.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/15963141/168599311-3f6794e5-f804-4ede-ab5f-fadb490c5d24.png">

**Comment by urfreespace** [comment]
fixed
