### ISSUE TITLE
Wrong position settings for GitHub Stars badge

### ISSUE THREAD

**Issue by SignorMercurio** [apache/pulsar-site#83]
## Current Behavior

GitHub Stars badge overlaps with the light/dark mode toggle button on a normal 1425-px laptop screen:

![image](https://user-images.githubusercontent.com/32540679/169027834-d4c18ccd-7b13-43f4-8ebb-11ae6c80e311.png)

When the browser window is resized to lower width, the badge will keep moving left:

![image](https://user-images.githubusercontent.com/32540679/169028046-00f3066a-b0dd-48af-b1fe-dda4f128c688.png)

## Expected Behavior

The badge and the toggle button should never overlap, even when the browser window is resized.

![image](https://user-images.githubusercontent.com/32540679/169029399-eabb7f73-93fc-4c67-a4a1-4467fe6dd7d0.png)

## Possible Reason

In [Line 193 in #77](https://github.com/apache/pulsar-site/pull/77/files#diff-09cf1119a5b3c2e7f9020e0631d965cc817f9ba589b4252cbb30ad92b403c4b6R193) a `right: 125px` style is introduced, leading to this issue.

## Possible Solution

Use `padding` instead of horizontal absolute positioning styles like `right`.

**Comment by SignorMercurio** [comment]
I would like to help with this. Could you please assign this issue to me?

**Comment by maxsxu** [comment]
> I would like to help with this. Could you please assign this issue to me?

@SignorMercurio  You should be able to use the `/assign` command

**Comment by Anonymitaet** [comment]
@zrsaber are you working on this issue?
https://github.com/apache/pulsar/issues/15550#issuecomment-1127168682

**Comment by zrsaber** [comment]
Yes, I'm working on this issue

**Comment by Anonymitaet** [comment]
Hi @SignorMercurio, thanks for your contribution! 
However @zrsaber was working on this issue several days ago, would you mind taking care of other issues? Feel free to pick your desired ones [here](https://github.com/apache/pulsar/issues?q=is%3Aopen+is%3Aissue+label%3Awebsite)

**Comment by zrsaber** [comment]
Okay, I'll pick some problems to solve

**Comment by Anonymitaet** [comment]
> Okay, I'll pick some problems to solve

No I mean @SignorMercurio would you mind taking care of other issues? Feel free to pick your desired ones [here](https://github.com/apache/pulsar/issues?q=is%3Aopen+is%3Aissue+label%3Awebsite)

@zrsaber please continue your work on the GitHub Icon issue, thanks

**Comment by urfreespace** [comment]
resolved.
